stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

build_action_server:
  stage: build
  image: action-server
  script:
    - cd action-server
    - npm ci
    - npm run build
  artifacts:
    paths:
      - action-server/dist

test_action_server:
  stage: test
  image: action-server
  script:
    - cd action-server
    - npm ci
    - npm run test
