version: 3

tasks:
  install:ollama:
    internal: true
    cmds:
      - sudo apt install portaudio19-dev
      - curl -fsSL https://ollama.com/install.sh | sh
      - ollama pull mxbai-embed-large
      - ollama pull llama3.2
      - ollama create homehome
    status:
      - ollama show llama3.2

  install:
    desc: Install voice actionizer
    deps:
      - task: install:ollama
    cmds:
      - brew install uv
      - uv sync

  run:
    desc: Run voice actionizer
    cmds:
      - uv run -- python -m ner.driving.stt.main

  store_albums:
    desc: Store albums metadata in Qdrant
    cmds:
      - uv run -- python -m ner.driving.cli.main store_albums

  chat:
    desc: Run voice actionizer in chat mode
    cmds:
      - uv run -- python -m ner.driving.chat.main
