version: 3

tasks:
  install:ollama:
    internal: true
    cmds:
      - curl -fsSL https://ollama.com/install.sh | sh
      - ollama pull phi3
    status:
      - ollama show phi3

  install:
    desc: Install voice actionizer
    deps:
      - task: install:ollama
    cmds:
      - pip install poetry
      - poetry install --no-root

  run:
    desc: Run voice actionizer
    cmds:
      - $(poetry env info -e) -m ner.driving.stt.main

  store_albums:
    desc: Store albums metadata in Qdrant
    cmds:
      - python -m ner.driving.cli.main store_albums

  chat:
    desc: Run voice actionizer in chat mode
    cmds:
      - python -m ner.driving.chat.main
