---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: download_source_code
    image: homehome_molecule_test
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/../../../vault.pw"
verifier:
  name: ansible
