---
- name: Is the Ollama service installed?
  ansible.builtin.command: ollama --version
  register: ollama_version
  ignore_errors: yes
  changed_when: false

- name: Install ollama
  ansible.builtin.shell: "curl -fsSL https://ollama.com/install.sh | sh"
  when: ollama_version.rc != 0

- name: Ensure model is pulled
  ansible.builtin.command: ollama show {{model}}
  register: model_status
  ignore_errors: yes
  changed_when: false

- name: Pull model
  ansible.builtin.shell: ollama pull {{model}}
  when: model_status.rc != 0
