---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - download_source_code

  tasks:
    - name: "Include local.action_server"
      ansible.builtin.include_role:
        name: "local.action_server"
