---
dependency:
  name: galaxy
driver:
   name: docker
platforms:
  - name: action_server
    image: homehome_molecule_test
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts_cache
      fact_caching_timeout: 7200
verifier:
  name: ansible
