Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider "virtualbox" do |v|
    v.name = "homehome"
    v.memory = 1024
    v.cpus = 2
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.hostname = "homehome"
  config.vm.network :private_network, ip: "192.168.56.7"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end

end
