---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: voice_actionizer
    image: homehome_molecule_test
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible

